# Configuration pour GitHub Pages (Jekyll)
title: cross-env-cmd
description: Un outil qui combine les fonctionnalités de cross-env et env-cmd
author: ValoriaTechnologia
email: contact@valoriatechnologia.com
baseurl: "/cross-env-cmd"
url: "https://valoriatechnologia.github.io"

# Configuration Jekyll
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore

# Inclusions
include:
  - _redirects

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"

# Navigation
navigation:
  - title: Accueil
    url: /cross-env-cmd/
  - title: Documentation
    url: /cross-env-cmd/docs/
  - title: Exemples
    url: /cross-env-cmd/examples/
  - title: GitHub
    url: https://github.com/ValoriaTechnologia/cross-env-cmd
  - title: npm
    url: https://www.npmjs.com/package/cross-env-cmd

# Social links
social:
  github: ValoriaTechnologia
  twitter: ValoriaTech
  linkedin: ValoriaTechnologia

# Build settings
sass:
  sass_dir: _sass
  style: compressed

# SEO
seo:
  type: "WebSite"
  name: "cross-env-cmd"
  description: "Un outil qui combine les fonctionnalités de cross-env et env-cmd"
  url: "https://valoriatechnologia.github.io/cross-env-cmd"
  image: "/cross-env-cmd/assets/logo.png"

